# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaldoPort' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaldoPort
  pod 'KakaoSDK'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  pod 'Kingfisher', '~> 5.0'

  target 'PaldoPortTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaldoPortUITests' do
    # Pods for testing
  end

end
